from http.server import BaseHTTPRequestHandler, HTTPServer
import json


class Handler(BaseHTTPRequestHandler):

    def do_POST(self):
        if self.path != "/api/v1/intelligence/analyze":
            self.send_response(404)
            self.end_headers()
            return

        content_length = int(
            self.headers.get("Content-Length", 0)
        )

        raw_body = self.rfile.read(content_length)

        try:
            request = json.loads(
                raw_body.decode("utf-8")
            )
        except json.JSONDecodeError:
            self.send_response(400)
            self.end_headers()
            return

        print("\n=== KNS Intelligence Request ===")
        print(
            json.dumps(
                request,
                indent=2
            )
        )

        score = (
            request
            .get("score", {})
            .get("overall", 0.0)
        )

        response = {
            "schema_version": "1.0",
            "analysis_id": "ana_mock_001",
            "status": "completed",
            "network_score": score,

            "summary":
                "Mock intelligence analysis completed successfully.",

            "findings": [
                {
                    "id": "finding_mock_1",
                    "severity": "low",
                    "category": "routing",
                    "title": "Mock routing observation",
                    "description":
                        "This finding was generated by the local mock backend.",
                    "affected_nodes": [],
                    "affected_links": []
                }
            ],

            "recommendations": [
                {
                    "id": "recommendation_mock_1",
                    "priority": "low",
                    "title": "Continue monitoring",
                    "description":
                        "No immediate structural intervention is required."
                }
            ]
        }

        payload = json.dumps(
            response
        ).encode("utf-8")

        self.send_response(200)

        self.send_header(
            "Content-Type",
            "application/json"
        )

        self.send_header(
            "Content-Length",
            str(len(payload))
        )

        self.end_headers()

        self.wfile.write(payload)


if __name__ == "__main__":
    server = HTTPServer(
        ("127.0.0.1", 8080),
        Handler
    )

    print(
        "Mock KNS Intelligence backend running at "
        "http://127.0.0.1:8080"
    )

    server.serve_forever()